#include "constants.h"

/* WARNING WARNING: these #defines must be kept in sync with syntaxis.h */
#if EXPORT_INTERFACE
#define TK_Unspecified                    135
#define TK_Unary_Expr                     134
#define TK_Target_List                    133
#define TK_Target                         132
#define TK_Stmt_List                      131
#define TK_Stmt                           130
#define TK_Small_Stmt_List                129
#define TK_Slice_Sfx                      128
#define TK_Slice_Expr                     127
#define TK_Return_Expr                    126
#define TK_Paren_Expr                     125
#define TK_Primary_Expr                   124
#define TK_Param_Star2                    123
#define TK_Param_Star                     122
#define TK_Param_Named                    121
#define TK_Param_List                     120
#define TK_Node_List                      119
#define TK_Loop_Vars                      118
#define TK_Load_Stmt                      117
#define TK_List_Expr                      116
#define TK_List_Comp                      115
#define TK_Lambda_Expr                    114
#define TK_Indent_Block                   113
#define TK_If_Stmt                        112
#define TK_If_Expr                        111
#define TK_For_Stmt                       110
#define TK_Expr_List                      109
#define TK_Expr                           108
#define TK_Dot_Sfx                        107
#define TK_Dot_Expr                       106
#define TK_Dict_Expr                      105
#define TK_Dict_Entry_List                104
#define TK_Dict_Entry                     103
#define TK_Dict_Comp                      102
#define TK_Def_Stmt                       101
#define TK_Def_Compound                   100
#define TK_Comp_Clause                    99
#define TK_Call_Sfx                       98
#define TK_Call_Expr                      97
#define TK_Build_File                     96
#define TK_Bin_Expr                       95
#define TK_Assign_Stmt                    94
#define TK_Attr_Value                     93
#define TK_Attr_Name                      92
#define TK_Attr                           91
#define TK_Arg_Star2                      90
#define TK_Arg_Star                       89
#define TK_Binding                        88
#define TK_Arg_List                       87
#define TK_YIELD                          86
#define TK_WITH                           85
#define TK_WHILE                          84
#define TK_VBAR_EQ                        83
#define TK_VBAR                           82
#define TK_TRY                            81
#define TK_TILDE                          80
#define TK_STRING                         79
#define TK_STAR2                          78
#define TK_STAR_EQ                        77
#define TK_STAR                           76
#define TK_SLASH                          75
#define TK_SEMI                           74
#define TK_RRANGLE_EQ                     73
#define TK_RRANGLE                        72
#define TK_RPAREN                         71
#define TK_RETURN                         70
#define TK_RBRACK                         69
#define TK_RBRACE                         68
#define TK_RANGLE                         67
#define TK_RAISE                          66
#define TK_PLUS_EQ                        65
#define TK_PLUS                           64
#define TK_PCT_EQ                         63
#define TK_PCT                            62
#define TK_PASS                           61
#define TK_OR                             60
#define TK_NOT                            59
#define TK_NONLOCAL                       58
#define TK_NEWLINE                        57
#define TK_MINUS_EQ                       56
#define TK_MINUS                          55
#define TK_LPAREN                         54
#define TK_LOAD                           53
#define TK_LLANGLE_EQ                     52
#define TK_LLANGLE                        51
#define TK_LE                             50
#define TK_LBRACK                         49
#define TK_LBRACE                         48
#define TK_LANGLE                         47
#define TK_LAMBDA                         46
#define TK_IS                             45
#define TK_IN                             44
#define TK_INT_OCT                        43
#define TK_INT_HEX                        42
#define TK_INT_DEC                        41
#define TK_INT                            40
#define TK_IMPORT                         39
#define TK_IF                             38
#define TK_ID                             37
#define TK_GLOBAL                         36
#define TK_GE                             35
#define TK_FROM                           34
#define TK_FOR                            33
#define TK_FLOAT                          32
#define TK_FLOAT_LIT                      31
#define TK_FINALLY                        30
#define TK_EXCEPT                         29
#define TK_BACKSLASH2                     28
#define TK_EQ2                            27
#define TK_EQ                             26
#define TK_ELSE                           25
#define TK_ELIF                           24
#define TK_DOT                            23
#define TK_SLASH_EQ                       22
#define TK_SLASH2_EQ                      21
#define TK_SLASH2                         20
#define TK_DEL                            19
#define TK_DEF                            18
#define TK_CONTINUE                       17
#define TK_COMMENT                        16
#define TK_COMMA                          15
#define TK_COLON                          14
#define TK_CLASS                          13
#define TK_CARET_EQ                       12
#define TK_CARET                          11
#define TK_BREAK                          10
#define TK_BLANK                           9
#define TK_BANG_EQ                         8
#define TK_BANG                            7
#define TK_ASSERT                          6
#define TK_AS                              5
#define TK_ARROW                           4
#define TK_AND                             3
#define TK_AMP_EQ                          2
#define TK_AMP                             1
#endif
