
#if EXPORT_INTERFACE
#define ESUNLARK_INVALID_ARG -1
#define ESUNLARK_ARG_TYPE_ERR -2
#define ESUNLARK_LOCN_ARG_ERR -3
#define EINDEX_TOO_BIG -4
#define EINVALID_ARG -5
#define EINVALID_ARG_LOAD -6
#define ENOT_FOUND -7
#define ENOT_FOUND_BINDING -8
#define ETOO_MANY_ARGS -9
#define ETOO_MANY_ARGS_BINDINGS -10
#define EMISSING_ARG_SELECTOR -11
#define EMISSING_ARG_BINDING -12
#define ENOT_IMPLEMENTED -13
#define EBAD_INDEX -14
#define EUNKNOWN_KW -15
#define EINVALID_VECINDEX -16
#define ENULL_BINDING_VAL -17
#define EINDEX_OUT_OF_BOUNDS -18
#define EINVALID_UPDATE -19

#endif

int e;
