
#if EXPORT_INTERFACE
#define ESUNLARK_INVALID_ARG -1
#define ESUNLARK_ARG_TYPE_ERR -2
#define ESUNLARK_LOCN_ARG_ERR -3
#define EINDEX_TOO_BIG -4
#define EINVALID_ARG -5
#define EINVALID_ARG_LOAD -6
#define ENOT_FOUND -7
#define ENOT_FOUND_BINDING -8
#define ETOO_MANY_ARGS -9
#define ETOO_MANY_ARGS_BINDINGS -10
#define EMISSING_ARG_SELECTOR -11
#define EMISSING_ARG_BINDING -12
#define ENOT_IMPLEMENTED -13
#define EINVALID_INDEX -14
#define EUNKNOWN_KW -15
#define EINVALID_VECINDEX -16
#define ENULL_BINDING_VAL -17
#define EINDEX_OUT_OF_BOUNDS -18
#define EINVALID_UPDATE -19
#define EINDEX_TYPE_ERR -20
#define EINVALID_REMOVE -21
#define EINVALID_INT_INDEX -22
#define EUNEXPECTED_STATE -23
#define EKW_NOT_NBR -24
#define ENOT_A_KW -25
#define ESPLICE_ARG -26
#define ESPLICE_BINDING_ARG -27
#define EUNKNOWN_C_OBJECT_TYPE -28
#define EMISSING_GET_SELECTOR -29
#define EINVALID_GET_SELECTOR -30
#define EINVALID_ACTION -31
#define EINVALID_SERIALIZE_AST -32
#define EINVALID_SERIALIZE_STARLARK -33
#define ESPLICE_ERR -34
#define EINVALID_LOAD_ARG -35
#define EINVALID_LOAD_ARG_VAL -36
#define EINVALID_LOAD_CTOR_ARGLIST -37
#define EINVALID_LOAD_CTOR_KEY -38
#define EINVALID_LOAD_CTOR_ARGS -39
#define EINVALID_LOAD_CTOR_ATTRS -40
#define EINVALID_LOAD_CTOR_ATTR -41
#define EINVALID_LOAD_NEWVAL -42
#define EINVALID_LOAD_SELECTOR -43
#define ESPLICE_LOADSTMT_ARG -44

#endif

int e;
